In [2]:
#6 DATA CLEANING 
#A. Find the position of missing values 
import numpy as np
salary=np.array([1000,2000,3000,4000,5000,6000,7000])
comm=np.array([10,20,30,None,None,None,None,None])
newcomm=np.where(comm==None,0,comm)
print(newcomm)

[10 20 30 0 0 0 0 0]


In [33]:
#6 DATA CLEANING 
#A. FIND THE POSITION OF MISSING VALUES IN NUMPY ARRAY
import numpy as np
sal=np.array([1000,2000,3000,4000,5000,2500,35000])
comm=np.array([10,20,30,None,None,25,None])
print("salary:")
print(sal)
print("comm:")
print(comm)
pos=np.where(comm==None)
print("\n Missing values positions are:\n",pos)



salary:
[ 1000  2000  3000  4000  5000  2500 35000]
comm:
[10 20 30 None None 25 None]

 Missing values positions are:
 (array([3, 4, 6]),)


In [32]:
#B. Drop rows that contain a missing value from a numpy array
import numpy as np
lst=[[1,2,np.nan],[3,4,5,],[6,7,8],[9,10,11]]
a=np.array(lst)
print("*"*40)
print("Numpy array")
print(a)
print("*"*40)
# syntax resobj=numpy.isnan(ndarrayobject)
#syntax any(pass axis)
print("Missing values from numpy array:\n")
print(a[np.isnan(a).any(axis=1)])
#syntax for dropping the rows
print("*"*40)
print("Drop rows that contain a missing value from a numpy array")
print(a[~np.isnan(a).any(axis=1)])

****************************************
Numpy array
[[ 1.  2. nan]
 [ 3.  4.  5.]
 [ 6.  7.  8.]
 [ 9. 10. 11.]]
****************************************
Missing values from numpy array:

[[ 1.  2. nan]]
****************************************
Drop rows that contain a missing value from a numpy array
[[ 3.  4.  5.]
 [ 6.  7.  8.]
 [ 9. 10. 11.]]


In [34]:
#C Replace all missing values with 0 in numpy array
sal=np.array([1000,2000,3000,4000,5000,6000,7000])
comm=np.array([10,20,30,None,None,None,None])
newcomm=np.where(comm==None,0,comm)
print("Replace all missing values with 0 in a numpy array")
print("content of",newcomm)
print("dimension",newcomm.ndim)
print("shape",newcomm.shape)
print("size",newcomm.size)
print("dtype",newcomm.dtype)
print("Netsalary")
net=sal+newcomm
print(net)

Replace all missing values with 0 in a numpy array
content of [10 20 30 0 0 0 0]
dimension 1
shape (7,)
size 7
dtype object
Netsalary
[1010 2020 3030 4000 5000 6000 7000]


In [37]:
lst=[[1,2,np.nan],[3,4,5,],[6,7,np.nan],[9,10,np.nan]]
a=np.array(lst)
print(a)
print("*"*40)
print("Finding the missing values=true/false")
print("*"*40)
np.isnan(a)

[[ 1.  2. nan]
 [ 3.  4.  5.]
 [ 6.  7. nan]
 [ 9. 10. nan]]
****************************************
Finding the missing values=true/false
****************************************


array([[False, False,  True],
       [False, False, False],
       [False, False,  True],
       [False, False,  True]])

In [7]:
lst=[[1,2,np.nan],[3,4,5,],[6,7,np.nan],[9,10,np.nan]]
a=np.array(lst)
print(a)
np.isnan(a)

[[ 1.  2. nan]
 [ 3.  4.  5.]
 [ 6.  7. nan]
 [ 9. 10. nan]]


array([[False, False,  True],
       [False, False, False],
       [False, False,  True],
       [False, False,  True]])

In [39]:
#d Drop all misising values from a numpy array
lst=[[1,2,3,None],[None,8,5,6],[7,8,None,9]]
a=np.array(lst)
print("ORIGINAL ARRAY:")
print(a)
res=np.extract(a!=None,a)
print("Drop all missing values from numpy array:")
print(res)

ORIGINAL ARRAY:
[[1 2 3 None]
 [None 8 5 6]
 [7 8 None 9]]
Drop all missing values from numpy array:
[1 2 3 8 5 6 7 8 9]
