In [1]:
a=10
print(a,type(a),id(a))

10 <class 'int'> 140712099812424


In [2]:
b=11.3
print(b,type(b),id(b))

11.3 <class 'float'> 2002342969296


In [3]:
c=True
print(c,type(c),id(c))

True <class 'bool'> 140712098343456


In [4]:
d=2+4j
print(d,type(d),id(d))

(2+4j) <class 'complex'> 2002342968880


In [7]:
#converting int data type int ndarray object
import numpy as np
a=10
print(a,type(a))
ndo=np.array(a)
print(ndo,type(ndo))
print("dimension",ndo.ndim)
print("data type",ndo.dtype)
print("shape ofndarray",ndo.shape)
print("size of ndarray",ndo.size)

10 <class 'int'>
10 <class 'numpy.ndarray'>
dimension 0
data type int32
shape ofndarray ()
size of ndarray 1


In [8]:
import numpy as np
a=14.5
print(a,type(a))
ndo=np.array(a)
print(ndo,type(ndo))
print("dimension",ndo.ndim)
print("data type",ndo.dtype)
print("shape of ndarray",ndo.shape)
print("size of ndarray",ndo.size)

14.5 <class 'float'>
14.5 <class 'numpy.ndarray'>
dimension 0
data type float64
shape of ndarray ()
size of ndarray 1


In [9]:
import numpy as np
a=True
print(a,type(a))
ndo=np.array(a)
print(ndo,type(ndo))
print("dimension",ndo.ndim)
print("data type",ndo.dtype)
print("shape of ndarray",ndo.shape)
print("size of ndarray",ndo.size)

True <class 'bool'>
True <class 'numpy.ndarray'>
dimension 0
data type bool
shape of ndarray ()
size of ndarray 1


In [10]:
import numpy as np
a=5+7j
print(a,type(a))
ndo=np.array(a)
print(ndo,type(ndo))
print("dimension",ndo.ndim)
print("data type",ndo.dtype)
print("shape of ndarray",ndo.shape)
print("size of ndarray",ndo.size)

(5+7j) <class 'complex'>
(5+7j) <class 'numpy.ndarray'>
dimension 0
data type complex128
shape of ndarray ()
size of ndarray 1


In [11]:
import numpy as np
a=range
print(a,type(a))
ndo=np.array(a)
print(ndo,type(ndo))
print("dimension",ndo.ndim)
print("data type",ndo.dtype)
print("shape of ndarray",ndo.shape)
print("size of ndarray",ndo.size)

<class 'range'> <class 'type'>
<class 'range'> <class 'numpy.ndarray'>
dimension 0
data type object
shape of ndarray ()
size of ndarray 1


In [12]:
import numpy as np
a=[10,14,31,"Rossum",True,(2+5j)]
print(a,type(a))
ndo=np.array(a)
print(ndo,type(ndo))
print("dimension",ndo.ndim)
print("data type",ndo.dtype)
print("shape of ndarray",ndo.shape)
print("size of ndarray",ndo.size)

[10, 14, 31, 'Rossum', True, (2+5j)] <class 'list'>
['10' '14' '31' 'Rossum' 'True' '(2+5j)'] <class 'numpy.ndarray'>
dimension 1
data type <U64
shape of ndarray (6,)
size of ndarray 6


In [13]:
list=[[10,20,30],[40,50,60],[70,80,90]]
print(list)
ndo=np.array(list)
print(ndo)

[[10, 20, 30], [40, 50, 60], [70, 80, 90]]
[[10 20 30]
 [40 50 60]
 [70 80 90]]


In [14]:
ls=[1,2,3]
ls2=[4,5,6]
ls3=ls+ls2
print(ls3)
nd1=np.array(ls)
nd2=np.array(ls2)
print(np.multiply(ls,ls2))

[1, 2, 3, 4, 5, 6]
[ 4 10 18]


In [21]:
ls=[1,2,3]
ls2=[4,5,6]
ls3=ls+ls2
print(ls3)
nd1=np.array(ls)
nd2=np.array(ls2)
print(nd1+nd2)
print(np.subtract(ls,ls2))

[1, 2, 3, 4, 5, 6]
[5 7 9]
[-3 -3 -3]


In [25]:
lst=[10,20,30,40]
print(lst,type(lst))
for i in lst:
    print (i)

[10, 20, 30, 40] <class 'list'>
10
20
30
40


In [28]:
import numpy as np
lst=[1,2,3,4,5,6,7,8,9]
print(lst)
ndo=np.array(lst)
print(ndo)
print("Dimension",ndo.ndim)
print("Type od nd",ndo.dtype)
print("Shape",ndo.shape)
print("Size",ndo.size)
ndo=ndo.reshape(3,3)
print(ndo)
print("Dimension",ndo.ndim)
print("Type od nd",ndo.dtype)
print("Shape",ndo.shape)
print("Size",ndo.size)

[1, 2, 3, 4, 5, 6, 7, 8, 9]
[1 2 3 4 5 6 7 8 9]
Dimension 1
Type od nd int32
Shape (9,)
Size 9
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Dimension 2
Type od nd int32
Shape (3, 3)
Size 9


In [30]:
import numpy as np
lst=range(0,4)
print(lst)
ndo=np.array(lst)
print(ndo)
print("Dimension",ndo.ndim)
print("Type od nd",ndo.dtype)
print("Shape",ndo.shape)
print("Size",ndo.size)
ndo=ndo.reshape(2,2)
print(ndo)
print("Dimension",ndo.ndim)
print("Type od nd",ndo.dtype)
print("Shape",ndo.shape)
print("Size",ndo.size)

range(0, 4)
[0 1 2 3]
Dimension 1
Type od nd int32
Shape (4,)
Size 4
[[0 1]
 [2 3]]
Dimension 2
Type od nd int32
Shape (2, 2)
Size 4


In [31]:
import numpy as np
lst=(1,2,3,4,5,6,7,8,9,10,11,12)
print(lst)
ndo=np.array(lst)
print(ndo)
print("Dimension",ndo.ndim)
print("Type od nd",ndo.dtype)
print("Shape",ndo.shape)
print("Size",ndo.size)
ndo=ndo.reshape(4,3)
print(ndo)
print("Dimension",ndo.ndim)
print("Type od nd",ndo.dtype)
print("Shape",ndo.shape)
print("Size",ndo.size)

(1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12)
[ 1  2  3  4  5  6  7  8  9 10 11 12]
Dimension 1
Type od nd int32
Shape (12,)
Size 12
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
Dimension 2
Type od nd int32
Shape (4, 3)
Size 12


In [36]:
import numpy as np
lst= {1: 'Geeks', 2: 'For', 3: 'Geeks', 4: 'yun', 5: 'rap'}
print(lst)
ndo=np.array(lst)
print(ndo)
print("Dimension",ndo.ndim)
print("Type od nd",ndo.dtype)
print("Shape",ndo.shape)
print("Size",ndo.size)
ndo=ndo.reshape(1,1)
print(ndo)
print("Dimension",ndo.ndim)
print("Type od nd",ndo.dtype)
print("Shape",ndo.shape)
print("Size",ndo.size)

{1: 'Geeks', 2: 'For', 3: 'Geeks', 4: 'yun', 5: 'rap'}
{1: 'Geeks', 2: 'For', 3: 'Geeks', 4: 'yun', 5: 'rap'}
Dimension 0
Type od nd object
Shape ()
Size 1
[[{1: 'Geeks', 2: 'For', 3: 'Geeks', 4: 'yun', 5: 'rap'}]]
Dimension 2
Type od nd object
Shape (1, 1)
Size 1
