In [2]:
#a create a 1d array
#working with arrays 
import numpy as np
nd=np.random.randint(1,100,size=10)
print("ID data")
print("Content of nd",nd)
print("type of nd",type(nd))
print("Dimension of nd",nd.ndim)
print("dtype of nd",nd.dtype)
print("shape of nd",nd.shape)
print("size of nd",nd.size)

ID data
Content of nd [52 45 72 75 42 14 50 82 55 80]
type of nd <class 'numpy.ndarray'>
Dimension of nd 1
dtype of nd int32
shape of nd (10,)
size of nd 10


In [3]:
#b Create a boolean array
lst=[0,1,2,3,0,6,7,8,0]
ndo=np.array(lst,dtype=bool)
print(ndo)
ndo=ndo.reshape(3,3)
print(ndo)
print("Dimension of ndo",ndo.ndim)
print("shape of ndo",ndo.shape)
print("Size of ndo",ndo.size)
print("dtype of ndo",ndo.dtype)

[False  True  True  True False  True  True  True False]
[[False  True  True]
 [ True False  True]
 [ True  True False]]
Dimension of ndo 2
shape of ndo (3, 3)
Size of ndo 9
dtype of ndo bool


In [4]:
#c extract items that staisfy a given condition from 1d arary
import numpy as np
ndo=np.random.randint(1,10,size=10)
print(ndo)
ind=np.where(ndo>5)
print(ind)
print(ndo[ind])


[2 2 9 8 4 9 1 5 3 9]
(array([2, 3, 5, 9], dtype=int64),)
[9 8 9 9]


In [5]:
#d. Replace items that satisfy a condition with another value in numpy
tstate=[10,20,15,18,25,70,56]
andhs=[25,19,30,45,67,89,90]
t=np.array(tstate)
a=np.array(andhs)
poll=np.where(t>18,t,a)
print(poll)

[25 20 30 45 25 70 56]


In [6]:
#e Replace items that satisfy a condition without affecting the original 
sal=np.array([1000,2000,3000,4000,5000,6000])
comm=np.array([10,20,30,None,None,None])
#netsal=sal+comm
newcomm=np.where(comm==None,0,comm)
print(newcomm)
netsal=sal+newcomm
print("Netsalary")
print(netsal)

[10 20 30 0 0 0]
Netsalary
[1010 2020 3030 4000 5000 6000]


In [8]:
#f Reshape an array
ndo=np.random.randint(1,50,size=(3,3))
print(ndo)
ndo1=ndo.reshape(9,)
print(ndo1)

[[29 14 19]
 [28 32  4]
 [44 28 27]]
[29 14 19 28 32  4 44 28 27]


In [9]:
#g Extract all numbers btwn a given range from a numpy array
ndo=np.random.randint(5,10,size=8)
print(ndo)
out=np.extract(ndo>5,ndo)
print(out)

[7 6 6 5 5 9 8 8]
[7 6 6 9 8 8]


In [26]:
#binary file-save
import numpy as np
lst=[10,20,30,40,50,60]
i=np.array
res=np.save("out",i)
print("File is saved successfully.....")

File is saved successfully.....


In [28]:
#binary file-load
result=np.load("out.npy")
print("File is loaded Successfully...")
print(result)

ValueError: Object arrays cannot be loaded when allow_pickle=False

In [30]:
lst=[100,200,300,400,500]
a=np.array(lst)
result=np.savetxt("outt.txt",a)
print("My text File is saved successfully")
print(result)

My text File is saved successfully
None


In [31]:
r=np.loadtxt("outt.txt")
print("My text file is loaded successfully")
print(r)

My text file is loaded successfully
[100. 200. 300. 400. 500.]


In [32]:
lst=[15,25,50,75.100]
c=np.array(lst)
r=np.savetxt("outc.csv",c,delimiter=',')
print("csv files saved successfully")

csv files saved successfully
